### ISSUE TITLE
s3 bucket host static html site

### ISSUE THREAD

**Issue by xuyuji9000** [coderbunker/aws-playground#8]
``` yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  StaticSiteBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: static-site
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  StaticSiteBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: '*'
          Action:
            - 's3:GetObject'
          Resource: !Join
              - ''
              - - !GetAtt StaticSiteBucket.Arn
                - /*
            # - 'arn:aws:s3:::example-bucket/*'
```
